# Font and appearance
font_family			SF Mono
bold_font			auto
italic_font			auto
bold_italic_font	auto

font_size			12.5

disable_ligatures	never

map alt+left  send_text all \x1b[1;3D
# Alt + Left Arrow
map alt+right send_text all \x1b[1;3C
# Alt + Right Arrow

# Colors
#background                #1e1e2e
#foreground                #cdd6f4
#selection_background      #6c7086

# Window title format
#window_title_format "{title} - kitty"

# Enable clipboard integration
#enable_clipboard_control yes

# Scrolling
#scrollback_lines 5000

# Mouse support
#map ctrl+shift+c copy_to_clipboard
#map ctrl+shift+v paste_from_clipboard
